# Generated by Django 5.2 on 2025-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faqs',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='blog.faq'),
        ),
    ]
