# Generated by Django 5.2 on 2025-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='faqs',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
