# Generated by Django 5.2 on 2025-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
