# Generated by Django 5.2 on 2025-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_trash',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_trash'], name='blog_commen_is_tras_bc63f3_idx'),
        ),
    ]
